on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build_and_test_sq:
    runs-on: ubuntu-latest
    name: Build and test SQ
    steps:
      - uses: actions/checkout@v2
      - uses: jonathanhaigh/sq-docker-build@20210305_5
        with:
          build_type: "release"
          coverage: true
          coveralls_repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}
